module.exports = [
    {title: 'Hawaii', src: 'https://cdn.shopify.com/s/files/1/2486/4354/products/Peter-Lik-Product-Hawaii-Book_1200x.png', format: 'book', orientation: null, edition: 'Library Collection', price: 95, collection: 'Library Collection', location: null, desc: "Featuring a screen-printed, fabric spine and 9mm blackboard, foil-debossed covers, each masterfully crafted book is finished with a black painted edging and fits perfectly in its magnetic closure slipcase. Peter Lik’s award-winning imagery comes to life on Stora Enso Fine Art Paper, with both matte and gloss varnishes.", prodInfo: "After visiting this exotic South Pacific for the first time decades ago, Peter Lik realized he had found exactly what he'd been searching for a paradise of lush forestry, clandestine waterfalls, fiery volcanoes, and crystal clear surf. Those initial moments set him on a passionate course of capturing the beauty of the islands year after year. Thousands of shots later, the Artist reveals his latest collection, highlighting a landscape that continues to evolve with every cascading stream of lava and every whispering breeze. Within this portfolio of over 160 newly revealed images, viewers will discover why this stunning archipelago is a true gift of the gods.", specs: ['Open Edition', 'Hardcover, 10" x 10" x 1.875", 272 pages', 'ISBN 978-0-9825412-4-1'], limitedInfo: null},
    
    {title: 'Evening Calm', src: 'https://cdn.shopify.com/s/files/1/2486/4354/products/Peter-Lik-Open-Edition-Evening_Calm_1800x.jpg', format: 'square', orientation: null, edition: 'Open Edition', price: 1800, collection: 'Open Editions', location: null, desc: 'Bring serenity into any interior with this eye-widening vision from Peter Lik. As night begins to appear along the quiet coastline, feel the cares of the world melt away. All that remains are its azure skies, and its misty waters carrying the worn out posts of an old jetty into the horizon.', specs: ['Scratch Resistant Acrylic Surface', 'Aluminum Recess Mount', 'Handcrafted in the USA', '29.5” x 29.5”'], limitedInfo: null},
    
    {title: '1859', src: 'https://cdn.shopify.com/s/files/1/2486/4354/products/Peter-Lik-1859-Framed-Recess-Mount_1800x.jpg', format: 'panorama', orientation: 'horizontal', edition: 'Limited Edition', price: null, collection: 'Architecture', location: 'Bodie, California', desc: 'High up in the mountains is the most classic ghost town I have ever seen. Bodie just oozes character and was actually once one of the largest cities in California. I returned to this classic town for the fourth day in a row when finally the weather changed. The last three days were bland, sunny skies, a death sentence for a landscape photographer. As an afternoon storm approached, I set up my angle. I spent hours searching for the spot to capture the magic of this town. I chose a 55mm lens and a nodal point to give this an interesting perspective. I waited to take the viewer right into the shot - it feels like you are standing underneath the veranda with me. This unique composition combined with moody skies gave the scene the mood I was chasing. Silent, high up in the desert, the smell of the sage and the sound of a creaking door in the wind gusts - ah, just love it!', specs: [], limitedInfo: '45 Artist Proof / 950 Limited Edition'},
    
    {title: 'Aviator B&W', src: 'https://cdn.shopify.com/s/files/1/2486/4354/products/Peter-Lik-Element-Pack-Display-Aviator-Black-and-White_1600x.png', format: null, orientation: null, edition: 'Element Pack', price: 495, collection: 'Element Packs', location: null, desc: "Give your atmosphere a sense of glory. Peter Lik’s passion for the flying war machines of yesteryear can be found in his sought after photographs from the ‘boneyards’ of the United States. In this tribute collection, journey back to WWII – a time when thunderous American aircraft were beacons of country pride and craftsmanship.", specs: ['Scratch Resistant Acrylic Surface', 'Komatex PVC Wall Mount', 'Handcrafted in the USA', 'Each Panel Measures 9.75” x 9.75”'], limitedInfo: null},
    
    {title: 'Bourbon Traditional Scoop Frame', src: 'https://cdn.shopify.com/s/files/1/2486/4354/products/Peter-Lik-Frame-Bourbon-Scoop-White-Liner-Classical_1400x.jpg', format: null, orientation: null, edition: 'Element Frame', price: 225, collection: 'Element Frames', location: null, desc: 'Add dimension to your Elements with this dark Olive Wood frame from Peter Lik, and feel his images come to life. Tones of charcoal and slate intertwine in this beautifully contoured design – which arcs towards its viewers and brings passion to its surroundings.', specs: ['Olive Wood Veneer', 'Hand Applied Beeswax Finish', 'Finger Jointed Hardwood Construction', 'Outside Dimension: 21.5" x 21.5"', 'Available Individually and in 4-Packs'], limitedInfo: null}
]